name: Checks

on:
  pull_request_target:
    types: [labeled]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  docs:
    if: >-
      github.event_name == 'push' ||
      (github.event.label.name == 'runner-approved' &&
       github.event.sender.login != github.event.pull_request.user.login &&
       github.event.pull_request.base.ref == 'main' &&
       github.event.pull_request.head.repo.full_name == github.repository &&
       github.event.pull_request.state == 'open')
    runs-on: [self-hosted, fargate, arm]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.3
          terraform_wrapper: false
      - name: Check Registry documentation
        run: make docs-check

  tests:
    if: >-
      github.event_name == 'push' ||
      (github.event.label.name == 'runner-approved' &&
       github.event.sender.login != github.event.pull_request.user.login &&
       github.event.pull_request.base.ref == 'main' &&
       github.event.pull_request.head.repo.full_name == github.repository &&
       github.event.pull_request.state == 'open')
    runs-on: [self-hosted, fargate, arm]
    env:
      TF_ACC: "0"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.3
          terraform_wrapper: false
      - name: Install race detector C compiler
        run: |
          if ! command -v gcc >/dev/null; then
            if [ "$(id -u)" -eq 0 ]; then
              apt-get update && apt-get install -y --no-install-recommends gcc libc6-dev
            else
              sudo apt-get update && sudo apt-get install -y --no-install-recommends gcc libc6-dev
            fi
          fi
      - name: Run Go tests with the race detector
        run: make test GO=go
