name: Checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.3
          terraform_wrapper: false
      - name: Check Registry documentation
        run: make docs-check

  tests:
    runs-on: ubuntu-latest
    env:
      TF_ACC: "0"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.3
          terraform_wrapper: false
      - name: Run Go tests with the race detector
        run: make test GO=go
